# Generated by Django 3.1.7 on 2021-03-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_businformation_bus_sourcetodestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='businformation',
            name='bus_viaroad',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
